# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from HWMonitoring import db

from typing import List, Dict  # noqa: F401

from HWMonitoring.models.base_model_ import Model
from HWMonitoring import util


class Machine(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)
    status = db.Column(db.String(64), index=True, unique=False)

    def __init__(self, id: int=None, name: str=None, status: str=None):  # noqa: E501
        """Machine - a model defined in Swagger

        :param id: The id of this Machine.  # noqa: E501
        :type id: int
        :param name: The name of this Machine.  # noqa: E501
        :type name: str
        :param status: The status of this Machine.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Machine':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Machine of this Machine.  # noqa: E501
        :rtype: Machine
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Machine.


        :return: The id of this Machine.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Machine.


        :param id: The id of this Machine.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Machine.


        :return: The name of this Machine.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Machine.


        :param name: The name of this Machine.
        :type name: str
        """

        self._name = name

    @property
    def status(self) -> str:
        """Gets the status of this Machine.


        :return: The status of this Machine.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Machine.


        :param status: The status of this Machine.
        :type status: str
        """
        allowed_values = ["RUN", "RUNNING", "STOPED", "STOPPING", "FAILED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
